apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgclu1
  namespace: pg1
spec:
  instances: 2
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: pg1-appuser
  superuserSecret:
    name: pg1-superuser
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/pgclu1
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Compatible: true
      insecure: true
      s3Credentials:
        accessKeyId:
          name: barman-minio
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: barman-minio
          key: AWS_SECRET_ACCESS_KEY
