apiVersion: v1
kind: Secret
metadata:
  name: pg1-superuser
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres123

---
apiVersion: v1
kind: Secret
metadata:
  name: pg1-appuser
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: appuser
  password: appuser123

