apiVersion: v1
kind: Secret
metadata:
  name: pg1-superuser
  namespace: pg1
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres123
---
apiVersion: v1
kind: Secret
metadata:
  name: pg1-appuser
  namespace: pg1
type: kubernetes.io/basic-auth
stringData:
  username: appuser
  password: appuser123
---
apiVersion: v1
kind: Secret
metadata:
  name: barman-minio
  namespace: pg1
type: kubernetes.io/basic-auth
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: admin123
---
