image:
  repository: ghcr.io/cloudnative-pg/cloudnative-pg
  pullPolicy: IfNotPresent
  tag: "1.27.1"

podLabels:
  env: "dev"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 1000m
    memory: 512Mi

livenessProbe:
  timeoutSeconds: 5
  periodSeconds: 10
readinessProbe:
  timeoutSeconds: 5
  periodSeconds: 10
startupProbe:
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 30
