apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-dev
  namespace: argocd-cnpg
spec:
  project: default
  source:
   repoURL: https://github.com/kmsarabu/cnpg.git
   targetRevision: dev
   path: charts/cloudnative-pg
   helm:
    valueFiles:
      - ../../env/dev/values.yaml
  destination:
   server: https://kubernetes.default.svc
   namespace: cnpg-system
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - createnamespace=true
     - ServerSideApply=true
